defaults: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['BIO_DB_NAME'] %>
  username: <%= ENV['BIO_DB_USER'] %>
  password: <%= ENV['BIO_DB_PASSWORD'] %>
  host: <%= ENV['BIO_DB_ENDPOINT'] %>